Description: Master stack
Parameters:
  CertificateArn:
    Type: String
  DomainName:
    Default: hyperboa.com
    Type: String
  Environment:
    Default: ''
    Type: String
  GithubOAuthToken:
    Description: Github access token
    Type: String
  GithubOwner:
    Default: ADBurpitt
    Description: Github repo owner
    Type: String
  GithubRepo:
    Default: idek-rn-bro
    Description: Github repo name
    Type: String
  ProjectSource:
    Default: https://github.com/adburpitt/idek-rn-bro
    Description: Source URL
    Type: String
Resources:
  Infrastructure:
    Properties:
      Parameters:
        CertificateArn:
          Ref: CertificateArn
        DomainName:
          Ref: DomainName
        Environment:
          Ref: Environment
      TemplateURL: https://s3.amazonaws.com/frankfurt-templates/7a0d62068ef0211ed6af5c915163bdbe.template
    Type: AWS::CloudFormation::Stack
  Pipeline:
    DependsOn: Infrastructure
    Properties:
      Parameters:
        ApiBuild:
          Fn::GetAtt:
          - Infrastructure
          - Outputs.ApiBuild
        Environment:
          Ref: Environment
        FrontendBuild:
          Fn::GetAtt:
          - Infrastructure
          - Outputs.ApiBuild
        GithubOAuthToken:
          Ref: GithubOAuthToken
        GithubOwner:
          Ref: GithubOwner
        GithubRepo:
          Ref: GithubRepo
        ProjectSource:
          Ref: ProjectSource
        StackName:
          Fn::GetAtt:
          - Infrastructure
          - Outputs.StackName
      TemplateURL: https://s3.amazonaws.com/frankfurt-templates/fb4cc3a674098705008a92050b633282.template
    Type: AWS::CloudFormation::Stack
