version: 0.2

environment_variables:
  plaintext:
    CHILD_TEMPLATES: |
      hosting.yaml
    TEMPLATE_FILES: |
      master.yaml
      hosting.yaml

# auth.yaml
# hosting.yaml
# database.yaml
# storage.yaml
# auth.yaml
# hosting.yaml
# database.yaml
# storage.yaml

phases:
  install:
    commands:
      - cd aws
      - npm install jsonlint -g

  pre_build:
    commands:
      - echo "Validating CFN templates"
      - |
        for cfn_template in $TEMPLATE_FILES; do
          echo "Validating CloudFormation template file $cfn_template"
          aws cloudformation validate-template --template-body file://$cfn_template
        done

  build:
    commands:
      - echo "Copying child stack templates to S3"
      - |
        for child_template in $CHILD_TEMPLATES; do
          if [ "X$TEMPLATE_PREFIX" = "X" ]; then
            aws s3 cp "$child_template" "s3://$TEMPLATE_BUCKET/$child_template"
          else
            aws s3 cp "$child_template" "s3://$TEMPLATE_BUCKET/$TEMPLATE_PREFIX/$child_template"
          fi
        done
      - |
        if [ "X$TEMPLATE_PREFIX" = "X" ]; then
          echo "Replacing \"TEMPLATE_PATH_PLACEHOLDER\" for \"$TEMPLATE_BUCKET\" in config.json"
          sed -i -e "s/TEMPLATE_PATH_PLACEHOLDER/$TEMPLATE_BUCKET/" config.json
        else
          echo "Replacing \"TEMPLATE_PATH_PLACEHOLDER\" for \"$TEMPLATE_BUCKET/$TEMPLATE_PREFIX\" in config.json"
          sed -i -e "s/TEMPLATE_PATH_PLACEHOLDER/$TEMPLATE_BUCKET\/$TEMPLATE_PREFIX/" config.json
        fi
      - |
        echo "Replacing \"ID_PLACEHOLDER\" for \"$DEPLOY_BUCKET_ID\" in config.json"
        sed -i -e "s/ID_PLACEHOLDER/$DEPLOY_BUCKET_ID/" config.json
      - |
        echo "Replacing \"DOMAIN_PLACEHOLDER\" for \"$DEPLOY_BUCKET_DOMAIN\" in config.json"
        sed -i -e "s/DOMAIN_PLACEHOLDER/$DEPLOY_BUCKET_DOMAIN/" config.json

artifacts:
  base-directory: aws
  type: zip
  files:
    - master.yaml
    - config.json