AWSTemplateFormatVersion: 2010-09-09
Description: Defines CDN/S3/Route53 for the frontend

Parameters:
  DeployBucketDomain:
    Type: String
  DeployBucketId:
    Type: String

Resources:
  Distribution:
      Type: "AWS::CloudFront::Distribution"
      Properties:
        DistributionConfig:
          Origins:
            - 
              DomainName: !Ref DeployBucketDomain
              Id: !Ref DeployBucketId
              S3OriginConfig:
                OriginAccessIdentity: ''
          DefaultRootObject: index.html
          Enabled: true
          DefaultCacheBehavior: 
            MinTTL: 86400
            MaxTTL: 31536000
            ForwardedValues: 
              QueryString: true
            TargetOriginId: !Ref DeployBucketId
            ViewerProtocolPolicy: "redirect-to-https"

# Output:
