AWSTemplateFormatVersion: 2010-09-09
Description: Defines CDN/S3/Route53 for the frontend

Resources:

  Distribution:
      Type: "AWS::CloudFront::Distribution"
      Properties:
        DistributionConfig:
          Origins:
            - 
              DomainName: !GetAtt DeployBucket.DomainName
              Id: !Ref DeployBucket
              S3OriginConfig:
                OriginAccessIdentity: ''
          DefaultRootObject: index.html
          Enabled: true
          DefaultCacheBehavior: 
            MinTTL: 86400
            MaxTTL: 31536000
            ForwardedValues: 
              QueryString: true
            TargetOriginId: !Ref DeployBucket
            ViewerProtocolPolicy: "redirect-to-https"

Output:
