Description: Master stack which creates all required nested stacks

Parameters:
  TemplatePath:
    Type: String
  Environment:
    Type: String
  DomainName:
    Type: String
  CertificateArn:
    Type: String

Resources:
  API:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://s3.${AWS::Region}.amazonaws.com/${TemplatePath}/API.json"
  
  DNS:
    Type: "AWS::CloudFormation::Stack"
    DependsOn: API
    Properties:
      TemplateURL: !Sub "https://s3.${AWS::Region}.amazonaws.com/${TemplatePath}/DNS.yaml"
      Parameters:
        Environment: !Ref Environment
        DomainName: !Ref DomainName
        CertificateArn: !Ref CertificateArn
        RestApiId: !GetAtt API.Outputs.RestApiId

  # SecurityStack:
  #   Type: "AWS::CloudFormation::Stack"
  #   Properties:
  #     TemplateURL: !Sub "https://s3.amazonaws.com/${TemplatePath}/security-stack.yml"
  #     Parameters:
  #       S3BucketName:
  #         Ref: S3BucketName
  #       VPCID:
  #         Ref: VPCID
  #       Environment:
  #         Ref: Environment
  #     Tags:
  #       - Key: Name
  #         Value: SecurityStack


# Outputs:
  # WebELBURL:
  #   Description: "URL endpoint of web ELB"
  #   Value: !GetAtt ServerStack.Outputs.WebELBURL
