Description: Master stack which creates all required nested stacks

Parameters:
  TemplatePath:
    Type: String
  DeployBucketId:
    Type: String
  DeployBucketDomain:
    Type: String
  # Environment:
  #   Type: String
  #   Description: Select the appropriate environment
  #   AllowedValues:
  #     - dev
  #     - beta
  #     - prod

Resources:
  Lambda:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://s3.${AWS::Region}.amazonaws.com/${TemplatePath}/lambda.json"
      # Parameters:
        # Environment: !Ref Environment
      Tags:
        - Key: Name
          Value: API
  
  CDN:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://s3.${AWS::Region}.amazonaws.com/${TemplatePath}/hosting.yaml"
      Parameters:
        DeployBucketDomain: !Ref DeployBucketDomain
        DeployBucketId: !Ref DeployBucketId
      Tags:
        - Key: Name
          Value: CDN

  # SecurityStack:
  #   Type: "AWS::CloudFormation::Stack"
  #   Properties:
  #     TemplateURL: !Sub "https://s3.amazonaws.com/${TemplatePath}/security-stack.yml"
  #     Parameters:
  #       S3BucketName:
  #         Ref: S3BucketName
  #       VPCID:
  #         Ref: VPCID
  #       Environment:
  #         Ref: Environment
  #     Tags:
  #       - Key: Name
  #         Value: SecurityStack


# Outputs:
  # WebELBURL:
  #   Description: "URL endpoint of web ELB"
  #   Value: !GetAtt ServerStack.Outputs.WebELBURL
