AWSTemplateFormatVersion: 2010-09-09
Description: Storage Buckets

# Parameters:
#   Environment:
#     Type: String

# Conditions:
#   isProd: !Equals
#     - !Ref Environment
#     - ''

Resources:
  TemplateBucket:
    Type: AWS::S3::Bucket
    # Properties:
    #   BucketName: !If
    #     - isProd
    #     - !Sub ${ProjectNameLowercase}-stack-bucket
    #     - !Sub ${ProjectNameLowercase}-${Environment}-stack-bucket

  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      # BucketName: !If
      #   - isProd
      #   - !Sub ${ProjectNameLowercase}-frontend-bucket
      #   - !Sub ${ProjectNameLowercase}-${Environment}-frontend-bucket
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

Outputs:
  TemplateBucket: 
    Value: !Ref TemplateBucket
  FrontendBucket:
    Value: !Ref FrontendBucket
  FrontendBucketDomainName:
    Value: !GetAtt FrontendBucket.DomainName