AWSTemplateFormatVersion: 2010-09-09
Description: Route53 and API Gateway custom domain.

Parameters:
  Environment:
    Type: String
  DomainName:
    Type: String
  CertificateArn:
    Type: String
  RestApiId:
    Type: String

Conditions:
  isProd: !Equals
    - !Ref Environment
    - ''

Resources:
  ApiDomainName:
    Type: 'AWS::ApiGateway::DomainName'
    Properties:
      DomainName: !If
        - isProd
        - !Sub api.test.${DomainName}
        - !Sub ${Environment}.api.test.${DomainName}
      CertificateArn: !Ref CertificateArn

  ApiMapping:
    Type: 'AWS::ApiGateway::BasePathMapping'
    DependsOn: ApiDomainName
    Properties:
      DomainName: !If
        - isProd
        - !Sub api.test.${DomainName}
        - !Sub ${Environment}.api.test.${DomainName}
      RestApiId: !Ref RestApiId
      Stage: Prod

  DNSRecord:
    Type: AWS::Route53::RecordSet
    DependsOn: ApiDomainName
    Properties:
      HostedZoneName: !Sub ${DomainName}.
      Name: !If
        - isProd
        - !Sub api.test.${DomainName}
        - !Sub ${Environment}.api.test.${DomainName}
      Type: A
      AliasTarget:
        DNSName: !GetAtt ApiDomainName.DistributionDomainName
        HostedZoneId: !GetAtt ApiDomainName.DistributionHostedZoneId
