AWSTemplateFormatVersion: 2010-09-09
Description: Frontend Cloudfront and Route53

Parameters:
  Environment:
    Type: String
  DomainName:
    Type: String
  CertificateArn:
    Type: String
  FrontendBucket:
    Type: String
  FrontendBucketDomainName:
    Type: String

Conditions:
  isProd: !Equals
    - !Ref Environment
    - ''

Resources:
  Distribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Aliases:
          - !If
            - isProd
            - !Sub app.${DomainName}
            - !Sub ${Environment}.app.${DomainName}
        Comment: !If
          - isProd
          - !Sub ${AWS::StackName}-Distribution
          - !Sub ${AWS::StackName}-${Environment}-Distribution
        Origins:
          - DomainName: !Ref FrontendBucketDomainName
            Id: !Ref FrontendBucket
            S3OriginConfig:
              OriginAccessIdentity: ''
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
        DefaultRootObject: index.html
        Enabled: true
        DefaultCacheBehavior: 
          MinTTL: 86400
          MaxTTL: 31536000
          ForwardedValues: 
            QueryString: true
          TargetOriginId: !Ref FrontendBucket
          ViewerProtocolPolicy: "redirect-to-https"

  FrontendDNSRecord:
    Type: AWS::Route53::RecordSet
    DependsOn: Distribution
    Properties:
      HostedZoneName: !Sub ${DomainName}.
      Name: !If
        - isProd
        - !Sub app.${DomainName}
        - !Sub ${Environment}.app.${DomainName}
      Type: A
      AliasTarget:
        DNSName: !GetAtt Distribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2 # For cloudfront distributions.

Outputs:
  Distribution:
    Value: !Ref Distribution