// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:7f5b3567-6db9-40ce-9d83-ad47605c55b1",
    "aws_cognito_region": "us-east-1"
};


export default awsmobile;
